package in.gov.grantsetu.enums;

public enum ApplicationStatus {
    SUBMITTED,
    FIELD_VERIFICATION_PENDING,
    FIELD_VERIFIED,
    DISTRICT_SCRUTINY_PENDING,
    DISTRICT_APPROVED,
    SANCTIONED,
    DISBURSEMENT_SCHEDULED,
    DISBURSED,
    REAPPLICATION_REQUIRED,
    REJECTED
}
